### ISSUE TITLE
Add custom Skybox

### ISSUE THREAD

**Issue by Ciborgm9** [Outer-Wilds-New-Horizons/nh-examples#14]
I Just think it would be a neat idea to make a custom skybox for the new star system as an example, since no other addon has one.

**Comment by Bwc9876** [comment]
Added the one from the 7th image on [this](https://assetstore.unity.com/packages/2d/textures-materials/sky/free-skyboxes-space-178953)

**Comment by Ciborgm9** [comment]
Oh nice, thank you!
